---
title: "Gathering Data"
author: "Westley Cook"
date: "2/27/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(janitor)
library(rvest)
library(stringr)
library(magrittr)
library(gridExtra)
library(blscrapeR)
library(gt)
library(broom)

```

MLB data downloaded as zip file from http://www.seanlahman.com/baseball-archive/statistics/

Somebody who did something similar to me:
https://courses.cs.washington.edu/courses/cse140/13wi/projects/mirae-report.pdf

```{r load-mlb-data, include=FALSE}

# loading data on mlb salaries

mlb_salaries_raw <- read_csv("data-files/mlb/salaries.csv") %>% 
  clean_names()

# loading data on mlb teams (which includes performance metrics)

mlb_teams <- read_csv("data-files/mlb/teams.csv") %>% 
  clean_names()

# wrangling salary data to create payroll data for each team and year

mlb_salaries <- mlb_salaries_raw %>% 
  group_by(team_id, year_id) %>% 
  summarize(payroll = sum(salary,
                          na.rm = TRUE))

# joining team salary data to team data so I have playoff performance and 
# payroll data in same dataframe

mlb_teams_salaries <- mlb_salaries %>% 
  right_join(mlb_teams, by = c("year_id", "team_id")) %>% 
  filter(year_id > 1984)

# reading in raw data on MLB regular season wins

mlb_rs_wins <- read_html("https://www.baseball-reference.com/leagues/MLB/") %>% 
  html_nodes("table") %>% 
  html_table() %>% 
  as.data.frame() %>% 
  na_if("") %>% 
  filter(G != "G")

# tidying and cleaning the regular season wins data to prep for joining with
# playoff performance and payroll data

mlb_rs_wins %<>% 
  pivot_longer(cols = ARI:WSN,
               names_to = "franch_id", 
               values_to = "rs_wins",
               values_drop_na = TRUE) %>% 
  rename(games_played = G,
         year = Year) %>% 
  mutate(year = as.numeric(year),
         games_played = as.numeric(games_played),
         rs_wins = as.numeric(rs_wins),
         franch_id = gsub("LAA", "ANA", franch_id),
         franch_id = gsub("MIA", "FLA", franch_id),
         franch_id = gsub("TBR", "TBD", franch_id))

```

```{r join-mlb-data, echo=FALSE}

# joining regular season win data with playoff performance and payroll data,
# filtering for the years in which I have payroll data available, wrangling to
# add a few variables, and selecting variables of interest

mlb_full <- mlb_rs_wins %>% 
  left_join(mlb_teams_salaries, by = c("franch_id", 
                                       "year" = "year_id")) %>% 
  filter(year <= 2016,
         year >= 1985) %>% 
  mutate(rs_win_pct = rs_wins / games_played,
         div_win = ifelse(rank == 1,
                          "Y",
                          "N")) %>% 
  select(year, franch_id, team_id, name, payroll,
         games_played, rs_wins, rs_win_pct,
         lg_id, rank, div_win, lg_win, ws_win)

# I don't have anything showing whether a team made the playoffs as a wildcard,
# but it's a bit complicated to figure that out so I'm leaving it be

```

NBA data downloaded as zip file from https://data.world/datadavis/nba-salaries

```{r load-nba-data, include=FALSE}

# reading in data on players in the NBA - don't need now, but it's here if I do
# later

nba_players <- read_csv("data-files/nba/players.csv") %>% 
  clean_names()

# reading in raw salary data for all players in the nba from 1984-85 to 2017-18

nba_salaries_raw <- read_csv("data-files/nba/salaries_1985to2018.csv") %>% 
  clean_names()

# wrangling to create salary data for each team and year

nba_salaries <- nba_salaries_raw %>% 
  group_by(team, season) %>% 
  summarize(team_salary = sum(salary))

# reading in and cleaning data on wins and postseason success, starting with
# just the atlanta hawks (because they're first alphabetically on the website
# the data comes from) - there was a lot going on here, so it was a line-by-line
# process over a period of time adding all the pieces I needed (as use can tell
# by the repeated calls of mutate and rename)

hawks <- read_html(
    "https://www.landofbasketball.com/teams/records_atlanta_hawks.htm") %>% 
  html_nodes("table") %>% 
  .[2] %>% 
  html_table() %>% 
  as.data.frame() %>% 
  slice(2, 5:38) %>% 
  row_to_names(1) %>% 
  clean_names() %>% 
  rename(conference = standing_2) %>% 
  rename(rs_win_pct = percent) %>% 
  rename(playoff_win_pct = percent_2) %>% 
  separate(w_l, into = c("wins", "losses"), sep = "-") %>% 
  separate(w_l_2, into = c("playoff_wins", "playoff_losses"), sep = "-") %>% 
  mutate(lockout = ifelse(season %>% endsWith(" *"), TRUE, FALSE)) %>% 
  mutate(season = ifelse(season %>% endsWith(" *"), 
                         season %>% substr(start = 1, stop = 7),
                         season)) %>% 

  # str_extract pattern to remove characters from would-be numeric (eg turn 14th
  # into 14) from here: http://stla.github.io/stlapblog/posts/Numextract.html
    
  mutate(standing = standing %>% str_extract("\\-*\\d+\\.*\\d*")) %>% 
  rename(conf_standing = standing) %>% 
  mutate(wins = as.numeric(wins),
         losses = as.numeric(losses),
         rs_win_pct = as.numeric(rs_win_pct),
         conf_standing = as.numeric(conf_standing),
         playoff_wins = as.numeric(playoff_wins),
         playoff_losses = as.numeric(playoff_losses),
         playoff_win_pct = as.numeric(playoff_win_pct)) %>% 
  mutate(franchise_id = "Hawks")

# since I needed to repeat this reading-in and cleaning process for 30 teams, I
# took the code I used to read in and clean the Hawks data and made a function
# out of it to use on all the other teams

team_season_data <- function(team_url, franchise_id){
  read_html(team_url) %>% 
  html_nodes("table") %>% 
  .[2] %>% 
  html_table() %>% 
  as.data.frame() %>% 
  slice(2, 5:38) %>% 
  row_to_names(1) %>% 
  clean_names() %>% 
  rename(conference = standing_2) %>% 
  rename(rs_win_pct = percent) %>% 
  rename(playoff_win_pct = percent_2) %>% 
  separate(w_l, into = c("wins", "losses"), sep = "-") %>% 
  separate(w_l_2, into = c("playoff_wins", "playoff_losses"), sep = "-") %>% 
  mutate(lockout = ifelse(season %>% endsWith(" *"), TRUE, FALSE)) %>% 
  mutate(season = ifelse(season %>% endsWith(" *"), 
                         season %>% substr(start = 1, stop = 7),
                         season)) %>% 
  mutate(standing = standing %>% str_extract("\\-*\\d+\\.*\\d*")) %>% 
  rename(conf_standing = standing) %>% 
  mutate(wins = as.numeric(wins),
         losses = as.numeric(losses),
         rs_win_pct = as.numeric(rs_win_pct),
         conf_standing = as.numeric(conf_standing),
         playoff_wins = as.numeric(playoff_wins),
         playoff_losses = as.numeric(playoff_losses),
         playoff_win_pct = as.numeric(playoff_win_pct)) %>% 
  mutate(franchise_id = franchise_id)
}

# reading in data for celtics

celtics <- team_season_data(
  "https://www.landofbasketball.com/teams/records_boston_celtics.htm",
  "Celtics"
)

# reading in data for nets

nets <- team_season_data(
  "https://www.landofbasketball.com/teams/records_brooklyn_nets.htm",
  "Nets"
)

# reading in data for hornets
# hornets only have 28 rows; started in 1988-89, missing 2002-03 and 2003-04

hornets <- team_season_data(
  "https://www.landofbasketball.com/teams/records_charlotte_hornets.htm",
  "Hornets/Bobcats"
)

# reading in data for bulls

bulls <- team_season_data(
  "https://www.landofbasketball.com/teams/records_chicago_bulls.htm",
  "Bulls"
)

# reading in data for cavs

cavs <- team_season_data(
  "https://www.landofbasketball.com/teams/records_cleveland_cavaliers.htm",
  "Cavaliers"
)

# reading in data for mavs

mavs <- team_season_data(
  "https://www.landofbasketball.com/teams/records_dallas_mavericks.htm",
  "Mavericks"
)

# reading in data for nuggets

nuggets <- team_season_data(
  "https://www.landofbasketball.com/teams/records_denver_nuggets.htm",
  "Nuggets"
)

# reading in data for pistons

pistons <- team_season_data(
  "https://www.landofbasketball.com/teams/records_detroit_pistons.htm",
  "Pistons"
)

# reading in data for warriors

warriors <- team_season_data(
  "https://www.landofbasketball.com/teams/records_golden_state_warriors.htm",
  "Warriors"
)

# reading in data for rockets

rockets <- team_season_data(
  "https://www.landofbasketball.com/teams/records_houston_rockets.htm",
  "Rockets"
)

# reading in data for pacers

pacers <- team_season_data(
  "https://www.landofbasketball.com/teams/records_indiana_pacers.htm",
  "Pacers"
)

# reading in data for clippers

clippers <- team_season_data(
  "https://www.landofbasketball.com/teams/records_los_angeles_clippers.htm",
  "Clippers"
)

# reading in data for lakers

lakers <- team_season_data(
  "https://www.landofbasketball.com/teams/records_los_angeles_lakers.htm",
  "Lakers"
)

# reading in data for grizzlies
# grizzlies only have 23 rows; started in 1995-96

grizzlies <- team_season_data(
  "https://www.landofbasketball.com/teams/records_memphis_grizzlies.htm",
  "Grizzlies"
)


# reading in data for heat
# heat only have 30 rows; started in 1988-89

heat <- team_season_data(
  "https://www.landofbasketball.com/teams/records_miami_heat.htm",
  "Heat"
)

# reading in data for bucks

bucks <- team_season_data(
  "https://www.landofbasketball.com/teams/records_milwaukee_bucks.htm",
  "Bucks"
)

# reading in data for twolves
# twolves only have 29 rows; started in 1989-90

twolves <- team_season_data(
  "https://www.landofbasketball.com/teams/records_minnesota_timberwolves.htm",
  "Timberwolves"
)

# reading in data for pelicans
# pelicans only have 16 rows; started in 2002-03

pelicans <- team_season_data(
  "https://www.landofbasketball.com/teams/records_new_orleans_pelicans.htm",
  "Pelicans/Hornets"
)

# reading in data for knicks

knicks <- team_season_data(
  "https://www.landofbasketball.com/teams/records_new_york_knicks.htm",
  "Knicks"
)

# reading in data for thunder and changing team name so it joins nicely with
# payroll data

thunder <- team_season_data(
  "https://www.landofbasketball.com/teams/records_oklahoma_city_thunder.htm",
  "Thunder/SuperSonics"
) %>% 
  mutate(team = gsub("Supersonics", "SuperSonics", team))

# reading in data for magic
# magic only have 29 rows; started in 1989-90

magic <- team_season_data(
  "https://www.landofbasketball.com/teams/records_orlando_magic.htm",
  "Magic"
)

# reading in data for 76ers

p76ers <- team_season_data(
  "https://www.landofbasketball.com/teams/records_philadelphia_76ers.htm",
  "76ers"
)

# reading in data for suns

suns <- team_season_data(
  "https://www.landofbasketball.com/teams/records_phoenix_suns.htm",
  "Suns"
)

# reading in data for blazers

blazers <- team_season_data(
  "https://www.landofbasketball.com/teams/records_portland_trailblazers.htm",
  "Trail Blazers"
)

# reading in data for kings

kings <- team_season_data(
  "https://www.landofbasketball.com/teams/records_sacramento_kings.htm",
  "Kings"
)

# reading in data for spurs

spurs <- team_season_data(
  "https://www.landofbasketball.com/teams/records_san_antonio_spurs.htm",
  "Spurs"
)

# reading in data for raptors
# raptors only have 23 rows; started in 1995-96

raptors <- team_season_data(
  "https://www.landofbasketball.com/teams/records_toronto_raptors.htm",
  "Raptors"
)

# reading in data for jazz (yay!)

jazz <- team_season_data(
  "https://www.landofbasketball.com/teams/records_utah_jazz.htm",
  "Jazz"
)

# reading in data for wizards (who knew, they used to be called the bullets)

wizards <- team_season_data(
  "https://www.landofbasketball.com/teams/records_washington_wizards.htm",
  "Wizards/Bullets"
)

```

```{r join-nba-data, echo=FALSE}

# putting all 30 teams in the same dataframe and standardizing performance
# factor levels (don't need to specify conference; I can group by conference if
# necessary since that variable already exists)

nba_team_performance <- bind_rows(blazers,
                              bucks,
                              bulls,
                              cavs,
                              celtics,
                              clippers,
                              grizzlies,
                              hawks,
                              heat,
                              hornets,
                              jazz,
                              kings,
                              knicks,
                              lakers,
                              magic,
                              mavs,
                              nets,
                              nuggets,
                              p76ers,
                              pacers,
                              pelicans,
                              pistons,
                              raptors,
                              rockets,
                              spurs,
                              suns,
                              thunder,
                              twolves,
                              warriors,
                              wizards) %>% 
  mutate(performance = gsub("DNQ", "Did not qualify", performance)) %>% 
  mutate(performance = gsub("Lost East Conf 1st Rd", "Lost 1st Round", performance)) %>% 
  mutate(performance = gsub("Lost West Conf 1st Rd", "Lost 1st Round", performance)) %>% 
  mutate(performance = gsub("Lost East Conf Semis", "Lost Conf Semis", performance)) %>% 
  mutate(performance = gsub("Lost West Conf Semis", "Lost Conf Semis", performance)) %>% 
  mutate(performance = gsub("Lost West Conf Finals", "Lost Conf Finals", performance)) %>% 
  mutate(performance = gsub("Lost East Conf Finals", "Lost Conf Finals", performance))

# checking to make sure I have all 30 franchises (and no more)

# nba_team_performance %>% 
#   group_by(franchise_id) %>% 
#   count()

# split nba_salaries variable team into two columns, one for team name and one
# for location, to prep for joining with performance dataframe

nba_salaries %<>% 
  mutate(location = word(team, start = 1, end = -2)) %>% 
  mutate(mascot = word(team, -1)) %>% 
  mutate(mascot = gsub("Blazers", "Trail Blazers", mascot)) %>% 
  mutate(location = gsub("Portland Trail", "Portland", location))

# joining performance data with payroll data, specifying column types, and
# changing some column names

nba_full <- nba_team_performance %>% 
  left_join(nba_salaries, by = c("team" = "mascot", "season")) %>% 
  mutate(season = as.factor(season)) %>% 
  mutate(year = as.numeric(substr(season, start = 1, stop = 4)) + 1) %>% 
  mutate(conference = as.factor(conference)) %>% 
  mutate(performance = as.factor(performance)) %>% 
  mutate(performance = fct_relevel(performance,
                                   "Did not qualify",
                                   "Lost 1st Round",
                                   "Lost Conf Semis",
                                   "Lost Conf Finals",
                                   "Lost NBA Finals",
                                   "NBA Champions")) %>% 
  mutate(franchise_id = as.factor(franchise_id)) %>% 
  rename(payroll = team_salary,
         full_team_name = team.y)

```

```{r gather-nhl-data}

# note: 2004-05 season missing due to lockout (no season)

read_html("https://en.wikipedia.org/wiki/List_of_team_payrolls_in_the_NHL") %>% 
  html_nodes(css = "table") %>% 
  html_table(fill = TRUE) %>% 
  .[5] %>% 
  as.data.frame() %>% 
  clean_names()  %>% 
  rename(payroll = team_payroll) %>% 
  select(year, payroll) %>% 
  mutate(location = rep("Carolina", nrow(.)),
         mascot = rep("Hurricanes", nrow(.)),
         team = paste(location, mascot, sep = " "),
         payroll = str_remove_all(payroll, "[$,]"),
         payroll = gsub("\\[.*", "", payroll),
         payroll = as.numeric(payroll),
         year = paste(substr(year, 0, 4), substr(year, 6, 7), sep = "-"),
         year = ifelse(year == "1999-20",
                       "1999-00",
                       year))

pull_nhl_payroll <- function(table_number, location, mascot){
  read_html(
    "https://en.wikipedia.org/wiki/List_of_team_payrolls_in_the_NHL") %>% 
  html_nodes(css = "table") %>% 
  html_table(fill = TRUE) %>% 
  .[table_number] %>% 
  as.data.frame() %>% 
  clean_names() %>% 
  rename(payroll = team_payroll) %>% 
  select(year, payroll) %>% 
  mutate(location = rep(location, nrow(.)),
         mascot = rep(mascot, nrow(.)),
         team = paste(location, mascot, sep = " "),
         payroll = str_remove_all(payroll, "[$,]"),
         payroll = gsub("\\[.*", "", payroll),
         payroll = as.numeric(payroll),
         year = paste(substr(year, 0, 4), substr(year, 6, 7), sep = "-"),
         year = ifelse(year == "1999-20",
                       "1999-00",
                       year))
}

# Eastern Conference, Metropolitan Division

t1 <- pull_nhl_payroll(5, "Carolina", "Hurricanes")

# note: Columbus was in Western Conference from 2000-01 to 2012-13

wt15 <- pull_nhl_payroll(6, "Columbus", "Blue Jackets")

t2 <- pull_nhl_payroll(7, "New Jersey", "Devils")

t3 <- pull_nhl_payroll(8, "New York", "Islanders")

t4 <- pull_nhl_payroll(9, "New York", "Rangers")

t5 <- pull_nhl_payroll(10, "Philadelphia", "Flyers")

t6 <- pull_nhl_payroll(11, "Pittsburgh", "Penguins")

t7 <- pull_nhl_payroll(12, "Washington", "Capitals")

# Eastern Conference, Atlantic Division

t8 <- pull_nhl_payroll(13, "Boston", "Bruins")

t9 <- pull_nhl_payroll(14, "Buffalo", "Sabres")

t10 <- pull_nhl_payroll(15, "Detroit", "Red Wings")

t11 <- pull_nhl_payroll(16, "Florida", "Panthers")

t12 <- pull_nhl_payroll(17, "Montreal", "Canadiens")

t13 <- pull_nhl_payroll(18, "Ottawa", "Senators")

t14 <- pull_nhl_payroll(19, "Tampa Bay", "Lightning")

t15 <- pull_nhl_payroll(20, "Toronto", "Maple Leafs")

# Western Conference, Central Division

wt1 <- pull_nhl_payroll(22, "Chicago", "Blackhawks")

wt2 <- pull_nhl_payroll(23, "Colorado", "Avalanche")

wt3 <- pull_nhl_payroll(24, "Dallas", "Stars")

wt4 <- pull_nhl_payroll(25, "Minnesota", "Wild")

wt5 <- pull_nhl_payroll(26, "Nashville", "Predators")

wt6 <- pull_nhl_payroll(27, "St. Louis", "Blues")

wt7 <- pull_nhl_payroll(28, "Atlanta", "Thrashers") # now Winnipeg Jets

# Western Conference, Pacific Division

wt8 <- pull_nhl_payroll(29, "Anaheim", "Ducks")

wt9 <- pull_nhl_payroll(30, "Arizona", "Coyotes")

wt10 <- pull_nhl_payroll(31, "Calgary", "Flames")

wt11 <- pull_nhl_payroll(32, "Edmonton", "Oilers")

wt12 <- pull_nhl_payroll(33, "Los Angeles", "Kings")

wt13 <- pull_nhl_payroll(34, "San Jose", "Sharks")

wt14 <- pull_nhl_payroll(35, "Vancouver", "Canucks")

# Vegas Golden Knights are a team, but only have payroll data starting in 2017

nhl_east_payroll <- bind_rows(t1,
                      t2,
                      t3,
                      t4,
                      t5,
                      t6,
                      t7,
                      t8,
                      t9,
                      t10,
                      t11,
                      t12,
                      t13,
                      t14,
                      t15) %>% 
  mutate(conference = "East")

nhl_west_payroll <- bind_rows(wt1,
                      wt2,
                      wt3,
                      wt4,
                      wt5,
                      wt6,
                      wt7,
                      wt8,
                      wt9,
                      wt10,
                      wt11,
                      wt12,
                      wt13,
                      wt14,
                      wt15) %>% 
  mutate(conference = "West")

nhl_payroll <- bind_rows(nhl_east_payroll,
                         nhl_west_payroll)

nhl_payroll %<>% 
  mutate(season = year,
         year = as.numeric(substr(year, 0, 4)) + 1,
         payroll_adjusted = map2_dbl(year, payroll, ~ inflation_calc(.x, .y)))






# standings data by team

pull_nhl_standings <- function(url){
 read_html(url) %>% 
  html_nodes(css = "table") %>% 
  html_table() %>% 
  as.data.frame() %>% 
  clean_names() %>% 
  select(everything(), -lg, -srs, -sos, -finish, -coaches) %>% 
  mutate(performance = playoffs,
         playoffs = ifelse(endsWith(team, "*"),
                           "yes",
                           "no"),
         team = ifelse(endsWith(team, "*"), 
                       str_remove(team, "\\*"),
                       team)) 
}

# team name changed from Mighty Ducks of Anaheim to Anaheim Ducks in 2006-07,
# but I'm ignoring that

ducks <- pull_nhl_standings(
  "https://www.hockey-reference.com/teams/ANA/history.html") %>% 
  mutate(team = rep("Anaheim Ducks", nrow(.)))

coyotes <- pull_nhl_standings(
  "https://www.hockey-reference.com/teams/PHX/history.html"
)

bruins <- pull_nhl_standings(
  "https://www.hockey-reference.com/teams/BOS/history.html"
)

sabres <- pull_nhl_standings(
  "https://www.hockey-reference.com/teams/BUF/history.html"
)

flames <- pull_nhl_standings(
  "https://www.hockey-reference.com/teams/CGY/history.html"
)

hurricanes <- pull_nhl_standings(
  "https://www.hockey-reference.com/teams/CAR/history.html"
)

blackhawks <- pull_nhl_standings(
  "https://www.hockey-reference.com/teams/CHI/history.html"
)

avalanche <- pull_nhl_standings(
  "https://www.hockey-reference.com/teams/COL/history.html"
)

blue_jackets <- pull_nhl_standings(
  "https://www.hockey-reference.com/teams/CBJ/history.html"
)

stars <- pull_nhl_standings(
  "https://www.hockey-reference.com/teams/DAL/history.html"
)

red_wings <- pull_nhl_standings(
  "https://www.hockey-reference.com/teams/DET/history.html"
)

oilers <- pull_nhl_standings(
  "https://www.hockey-reference.com/teams/EDM/history.html"
)

panthers <- pull_nhl_standings(
  "https://www.hockey-reference.com/teams/FLA/history.html"
)

kings <- pull_nhl_standings(
  "https://www.hockey-reference.com/teams/LAK/history.html"
)

wild <- pull_nhl_standings(
  "https://www.hockey-reference.com/teams/MIN/history.html"
)

canadiens <- pull_nhl_standings(
  "https://www.hockey-reference.com/teams/MTL/history.html"
)

predators <- pull_nhl_standings(
  "https://www.hockey-reference.com/teams/NSH/history.html"
)

devils <- pull_nhl_standings(
  "https://www.hockey-reference.com/teams/NJD/history.html"
)

islanders <- pull_nhl_standings(
  "https://www.hockey-reference.com/teams/NYI/history.html"
)

rangers <- pull_nhl_standings(
  "https://www.hockey-reference.com/teams/NYR/history.html"
)

senators <- pull_nhl_standings(
  "https://www.hockey-reference.com/teams/OTT/history.html"
)

flyers <- pull_nhl_standings(
  "https://www.hockey-reference.com/teams/PHI/history.html"
)

penguins <- pull_nhl_standings(
  "https://www.hockey-reference.com/teams/PIT/history.html"
)

sharks <- pull_nhl_standings(
  "https://www.hockey-reference.com/teams/SJS/history.html"
)

blues <- pull_nhl_standings(
  "https://www.hockey-reference.com/teams/STL/history.html"
)

lightning <- pull_nhl_standings(
  "https://www.hockey-reference.com/teams/TBL/history.html"
)

maple_leafs <- pull_nhl_standings(
  "https://www.hockey-reference.com/teams/TOR/history.html"
)

canucks <- pull_nhl_standings(
  "https://www.hockey-reference.com/teams/VAN/history.html"
)

capitals <- pull_nhl_standings(
  "https://www.hockey-reference.com/teams/WSH/history.html"
)

thrashers <- pull_nhl_standings(
  "https://www.hockey-reference.com/teams/WPG/history.html"
)



nhl_performance <- bind_rows(ducks,
                             coyotes,
                             bruins,
                             sabres,
                             flames,
                             hurricanes,
                             blackhawks,
                             avalanche,
                             blue_jackets,
                             stars,
                             red_wings,
                             oilers,
                             panthers,
                             kings,
                             wild,
                             canadiens,
                             predators,
                             devils,
                             islanders,
                             rangers,
                             senators,
                             flyers,
                             penguins,
                             sharks,
                             blues,
                             lightning,
                             maple_leafs,
                             canucks,
                             capitals,
                             thrashers)

nhl_performance

```

```{r adjust-for-inflation, echo=FALSE}

# loading in tibble with CPI values to use in adjusting for inflation

i2020 <- inflation_adjust(2020)

# function to calculate dollar amount from some past year to 2020 dollars

inflation_calc <- function(then_year, amount){
  then_cpi <- i2020 %>% 
    filter(year == then_year) %>% 
    pull(avg_cpi)
  now_cpi <- i2020 %>% 
    filter(year == 2020) %>% 
    pull(avg_cpi)
  
  amount * now_cpi / then_cpi
}

# adjust mlb data for inflation, adding one column with inflation adjustments
# for each year and another column with payroll rank for each year (how much a
# team spent relative to other teams, 1 is lowest and 30 is highest)

mlb_adjusted <- mlb_full %>% 
  mutate(
    payroll_adjusted = map2_dbl(year, payroll, ~ inflation_calc(.x, .y))) %>% 
  rename(franchise_id = franch_id) %>% 
  group_by(year) %>% 
  mutate(payroll_rank = rank(payroll))

# adjust nba data for inflation using the same process

nba_adjusted <- nba_full %>% 
  mutate(payroll_adjusted = map2_dbl(year, payroll,
                                     ~ inflation_calc(.x, .y))) %>% 
  group_by(season) %>% 
  mutate(payroll_rank = rank(payroll))

nba_adjusted

# NOTE: missing payroll data for
# 1986-87 Trail Blazers
# 1986-87 Bucks
# 1986-87 Clippers
# 1986-87 Kings
# 1986-87 Lakers
# 1986-87 SuperSonics
# 1986-87 Warriors
# 1989-90 Magic
# 1989-90 Pacers
# 1989-90 Timberwolves

```

```{r save-to-rdata, echo=FALSE}

save(mlb_adjusted, file = "shiny/data-files/mlb.Rdata")
save(nba_adjusted, file = "shiny/data-files/nba.Rdata")
save(nba_adjusted, mlb_adjusted, file = "data-files/mlb&nba.Rdata")

```

Could scrape NHL data from here if so inclined:
https://en.wikipedia.org/wiki/List_of_team_payrolls_in_the_NHL

