---
title: "Milestone 4"
author: "Westley Cook"
date: "3/6/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(janitor)
library(rvest)

hawks <- read_html(
    "https://www.landofbasketball.com/teams/records_atlanta_hawks.htm") %>% 
  html_nodes("table") %>% 
  .[2] %>% 
  html_table() %>% 
  as.data.frame() %>% 
  slice(2, 5:38) %>% 
  row_to_names(1) %>% 
  clean_names() %>% 
  rename(conference = standing_2) %>% 
  rename(rs_win_pct = percent) %>% 
  rename(playoff_win_pct = percent_2) %>% 
  separate(w_l, into = c("wins", "losses"), sep = "-") %>% 
  separate(w_l_2, into = c("playoff_wins", "playoff_losses"), sep = "-") %>% 
  mutate(lockout = ifelse(season %>% endsWith(" *"), TRUE, FALSE)) %>% 
  mutate(season = ifelse(season %>% endsWith(" *"), 
                         season %>% substr(start = 1, stop = 7),
                         season)) %>% 

# pattern from here: http://stla.github.io/stlapblog/posts/Numextract.html  
    
  mutate(standing = standing %>% str_extract("\\-*\\d+\\.*\\d*")) %>% 
  rename(conf_standing = standing) %>% 
  mutate(wins = as.numeric(wins),
         losses = as.numeric(losses),
         rs_win_pct = as.numeric(rs_win_pct),
         conf_standing = as.numeric(conf_standing),
         playoff_wins = as.numeric(playoff_wins),
         playoff_losses = as.numeric(playoff_losses),
         playoff_win_pct = as.numeric(playoff_win_pct))

team_season_data <- function(team_url){
  read_html(team_url) %>% 
  html_nodes("table") %>% 
  .[2] %>% 
  html_table() %>% 
  as.data.frame() %>% 
  slice(2, 5:38) %>% 
  row_to_names(1) %>% 
  clean_names() %>% 
  rename(conference = standing_2) %>% 
  rename(rs_win_pct = percent) %>% 
  rename(playoff_win_pct = percent_2) %>% 
  separate(w_l, into = c("wins", "losses"), sep = "-") %>% 
  separate(w_l_2, into = c("playoff_wins", "playoff_losses"), sep = "-") %>% 
  mutate(lockout = ifelse(season %>% endsWith(" *"), TRUE, FALSE)) %>% 
  mutate(season = ifelse(season %>% endsWith(" *"), 
                         season %>% substr(start = 1, stop = 7),
                         season)) %>% 
  mutate(standing = standing %>% str_extract("\\-*\\d+\\.*\\d*")) %>% 
  rename(conf_standing = standing) %>% 
  mutate(wins = as.numeric(wins),
         losses = as.numeric(losses),
         rs_win_pct = as.numeric(rs_win_pct),
         conf_standing = as.numeric(conf_standing),
         playoff_wins = as.numeric(playoff_wins),
         playoff_losses = as.numeric(playoff_losses),
         playoff_win_pct = as.numeric(playoff_win_pct))
}

celtics <- team_season_data(
  "https://www.landofbasketball.com/teams/records_boston_celtics.htm")

nets <- team_season_data(
  "https://www.landofbasketball.com/teams/records_brooklyn_nets.htm"
)

# hornets only have 28 rows; started in 1988-89, missiong 2002-03 and 2003-04

hornets <- team_season_data(
  "https://www.landofbasketball.com/teams/records_charlotte_hornets.htm"
)

bulls <- team_season_data(
  "https://www.landofbasketball.com/teams/records_chicago_bulls.htm"
)

cavs <- team_season_data(
  "https://www.landofbasketball.com/teams/records_cleveland_cavaliers.htm"
)

mavs <- team_season_data(
  "https://www.landofbasketball.com/teams/records_dallas_mavericks.htm"
)

nuggets <- team_season_data(
  "https://www.landofbasketball.com/teams/records_denver_nuggets.htm"
)

pistons <- team_season_data(
  "https://www.landofbasketball.com/teams/records_detroit_pistons.htm"
)

warriors <- team_season_data(
  "https://www.landofbasketball.com/teams/records_golden_state_warriors.htm"
)

rockets <- team_season_data(
  "https://www.landofbasketball.com/teams/records_houston_rockets.htm"
)

pacers <- team_season_data(
  "https://www.landofbasketball.com/teams/records_indiana_pacers.htm"
)

clippers <- team_season_data(
  "https://www.landofbasketball.com/teams/records_los_angeles_clippers.htm"
)

lakers <- team_season_data(
  "https://www.landofbasketball.com/teams/records_los_angeles_lakers.htm"
)

# grizzlies only have 23 rows; started in 1995-96

grizzlies <- team_season_data(
  "https://www.landofbasketball.com/teams/records_memphis_grizzlies.htm"
)

# heat only have 30 rows; started in 1988-89

heat <- team_season_data(
  "https://www.landofbasketball.com/teams/records_miami_heat.htm"
)

bucks <- team_season_data(
  "https://www.landofbasketball.com/teams/records_milwaukee_bucks.htm"
)

# twolves only have 29 rows; started in 1989-90

twolves <- team_season_data(
  "https://www.landofbasketball.com/teams/records_minnesota_timberwolves.htm"
)

# pelicans only have 16 rows; started in 2002-03

pelicans <- team_season_data(
  "https://www.landofbasketball.com/teams/records_new_orleans_pelicans.htm"
)

knicks <- team_season_data(
  "https://www.landofbasketball.com/teams/records_new_york_knicks.htm"
)

thunder <- team_season_data(
  "https://www.landofbasketball.com/teams/records_oklahoma_city_thunder.htm"
)

# magic only have 29 rows; started in 1989-90

magic <- team_season_data(
  "https://www.landofbasketball.com/teams/records_orlando_magic.htm"
)

p76ers <- team_season_data(
  "https://www.landofbasketball.com/teams/records_philadelphia_76ers.htm"
)

suns <- team_season_data(
  "https://www.landofbasketball.com/teams/records_phoenix_suns.htm"
)

blazers <- team_season_data(
  "https://www.landofbasketball.com/teams/records_portland_trailblazers.htm"
)

kings <- team_season_data(
  "https://www.landofbasketball.com/teams/records_sacramento_kings.htm"
)

spurs <- team_season_data(
  "https://www.landofbasketball.com/teams/records_san_antonio_spurs.htm"
)

# raptors only have 23 rows; started in 1995-96

raptors <- team_season_data(
  "https://www.landofbasketball.com/teams/records_toronto_raptors.htm"
)

jazz <- team_season_data(
  "https://www.landofbasketball.com/teams/records_utah_jazz.htm"
)

wizards <- team_season_data(
  "https://www.landofbasketball.com/teams/records_washington_wizards.htm"
)
```

## Progress

Since last week, I've scraped and cleaned win-loss data from tables on www.landofbasketball.com for all NBA teams from the 1984-85 season up to the 2017-18 season (the same range of dates as is covered by my team payroll data). The data also contains information on whether a team made the playoffs, and if so, how they did (whether they won the championship, or in which round they lost).

I first scraped data for the Atlanta Hawks (because they were the first team in alphabetical order, and thus the first listed on the website). The table was not very clean, so I took a number of steps to clean up the data. I sliced the rows I wanted, broke the hyphenated win-loss columns into separate win columns and loss columns, added a logical variable to show which seasons were shortened by lockouts, edited text strings in the season column and in the standings column so they were purely numerical, and converted variable types (all of which were characters originally) into appropriate formats (doubles, mostly).

I then put that whole process in a function with one argument (url) and used it to load and clean data for the remaining NBA teams by just calling that function with the url for the page with the table for each team.

My code is all available in this file (ms_4.Rmd) and my repo is available at https://github.com/westleycook/gov-1005-final-project

The next step with this data is to join it all together into a tidy tibble with team wins and losses for every team in the NBA over the relevant time period, which should be fairly simple. I'll then need to join the win-loss dataframe with the payroll dataframe to be able to generate useful plots and run analyses about the effect of payroll on win-loss and other success metrics.